/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import clases.controlador;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class InterAdmin extends javax.swing.JFrame {


    public InterAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jVervuelos1 = new javax.swing.JButton();
        jAñadirvuelos2 = new javax.swing.JButton();
        jEditarvuelos3 = new javax.swing.JButton();
        jCancelarvuelos4 = new javax.swing.JButton();
        jInformaciondcliente5 = new javax.swing.JButton();
        jAñadirAdministrador6 = new javax.swing.JButton();
        jSalir1 = new javax.swing.JButton();
        jVolverinicio2 = new javax.swing.JButton();
        jFondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jVervuelos1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jVervuelos1.setText("Añadir Vuelos");
        jVervuelos1.setBorder(null);
        jVervuelos1.setBorderPainted(false);
        jVervuelos1.setContentAreaFilled(false);
        jVervuelos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jVervuelos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 192, 560, 60));

        jAñadirvuelos2.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jAñadirvuelos2.setText("Ver Vuelos");
        jAñadirvuelos2.setBorder(null);
        jAñadirvuelos2.setBorderPainted(false);
        jAñadirvuelos2.setContentAreaFilled(false);
        jAñadirvuelos2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jAñadirvuelos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 560, 60));

        jEditarvuelos3.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jEditarvuelos3.setText("Editar Vuelos");
        jEditarvuelos3.setBorder(null);
        jEditarvuelos3.setBorderPainted(false);
        jEditarvuelos3.setContentAreaFilled(false);
        jEditarvuelos3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jEditarvuelos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarvuelos3ActionPerformed(evt);
            }
        });
        jPanel1.add(jEditarvuelos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 560, 50));

        jCancelarvuelos4.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jCancelarvuelos4.setText("Cancelar Vuelos");
        jCancelarvuelos4.setBorder(null);
        jCancelarvuelos4.setBorderPainted(false);
        jCancelarvuelos4.setContentAreaFilled(false);
        jCancelarvuelos4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jCancelarvuelos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 452, 560, 50));

        jInformaciondcliente5.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jInformaciondcliente5.setText("Informacion Del Cliente");
        jInformaciondcliente5.setBorder(null);
        jInformaciondcliente5.setBorderPainted(false);
        jInformaciondcliente5.setContentAreaFilled(false);
        jInformaciondcliente5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jInformaciondcliente5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 542, 560, 60));

        jAñadirAdministrador6.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jAñadirAdministrador6.setText("Añadir Administrador");
        jAñadirAdministrador6.setBorder(null);
        jAñadirAdministrador6.setBorderPainted(false);
        jAñadirAdministrador6.setContentAreaFilled(false);
        jAñadirAdministrador6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jAñadirAdministrador6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jAñadirAdministrador6MousePressed(evt);
            }
        });
        jPanel1.add(jAñadirAdministrador6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 632, 560, 60));

        jSalir1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jSalir1.setText("Salir");
        jSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalir1ActionPerformed(evt);
            }
        });
        jPanel1.add(jSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 680, -1, -1));

        jVolverinicio2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jVolverinicio2.setText("Volver al inicio ");
        jVolverinicio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jVolverinicio2MousePressed(evt);
            }
        });
        jPanel1.add(jVolverinicio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 680, -1, -1));

        jFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Tabla con 3 columnas.png"))); // NOI18N
        jFondo1.setText("jLabel1");
        jPanel1.add(jFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1362, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEditarvuelos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarvuelos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEditarvuelos3ActionPerformed

    private void jSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jSalir1ActionPerformed

    private void jAñadirAdministrador6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAñadirAdministrador6MousePressed
        String userr = JOptionPane.showInputDialog("Ingrese el nombre de usuario del nuevo administrador");
        String password = JOptionPane.showInputDialog("Ingrese la contraseña del nuevo adminsitrador");
        JOptionPane.showMessageDialog(null, "Usuario creado exitosamente", "Register",  JOptionPane.YES_OPTION);
        
    }//GEN-LAST:event_jAñadirAdministrador6MousePressed

    private void jVolverinicio2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVolverinicio2MousePressed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jVolverinicio2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAñadirAdministrador6;
    private javax.swing.JButton jAñadirvuelos2;
    private javax.swing.JButton jCancelarvuelos4;
    private javax.swing.JButton jEditarvuelos3;
    private javax.swing.JLabel jFondo1;
    private javax.swing.JButton jInformaciondcliente5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSalir1;
    private javax.swing.JButton jVervuelos1;
    private javax.swing.JButton jVolverinicio2;
    // End of variables declaration//GEN-END:variables
}
