/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author SUBLIMINADOS
 */
public class Interfaz_prinipal extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_prinipal
     */
    public Interfaz_prinipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btncompra = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnchekin1 = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncompra.setFont(new java.awt.Font("Sitka Text", 1, 48)); // NOI18N
        btncompra.setText("COMPRA DE VUELOS");
        btncompra.setBorder(null);
        btncompra.setBorderPainted(false);
        btncompra.setContentAreaFilled(false);
        btncompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncompra.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        btncompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncompraActionPerformed(evt);
            }
        });
        jPanel1.add(btncompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 720, 60));

        btnsalir.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.setBorder(null);
        btnsalir.setBorderPainted(false);
        btnsalir.setContentAreaFilled(false);
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, 730, 60));

        btnchekin1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnchekin1.setText("CHECK-IN");
        btnchekin1.setBorder(null);
        btnchekin1.setBorderPainted(false);
        btnchekin1.setContentAreaFilled(false);
        btnchekin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnchekin1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnchekin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchekin1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnchekin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 730, 60));

        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnlogin.setText("LOGIN (ADMINISTRATIVOS)");
        btnlogin.setBorder(null);
        btnlogin.setBorderPainted(false);
        btnlogin.setContentAreaFilled(false);
        btnlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 730, 60));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tabla con 3 columnas (1).png"))); // NOI18N
        Fondo.setText("jLabel1");
        Fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1360, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncompraActionPerformed
        this.setVisible(false);
        new interfaz2().setVisible(true);
    }//GEN-LAST:event_btncompraActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnchekin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchekin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnchekin1ActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
        
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_prinipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_prinipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_prinipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_prinipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_prinipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnchekin1;
    private javax.swing.JButton btncompra;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsalir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
