/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author USER
 */
public class interfaz2 extends javax.swing.JFrame {

    /**
     * Creates new form interfaz2
     */
    public interfaz2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jvuelos1 = new javax.swing.JComboBox<>();
        jEquipajeadi2 = new javax.swing.JComboBox<>();
        jHora3 = new javax.swing.JComboBox<>();
        jCONFIRMAR1 = new javax.swing.JButton();
        jvolver1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jfondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jvuelos1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jvuelos1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Ctg- Bogota - $220000", "Ctg- Medellin - $300000", "Ctg- Cali $260000" }));
        jvuelos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jvuelos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvuelos1ActionPerformed(evt);
            }
        });
        jPanel2.add(jvuelos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        jEquipajeadi2.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jEquipajeadi2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", "Maleta 23KG- 600000", "Morral Personal  6KG- 300000", "NO" }));
        jEquipajeadi2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jEquipajeadi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, -1, -1));

        jHora3.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jHora3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "06:00am - 08:00am", "13:00pm - 15:00pm", "18:00pm - 20:00pm " }));
        jHora3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jHora3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, -1, -1));

        jCONFIRMAR1.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jCONFIRMAR1.setText("Confirmar");
        jCONFIRMAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCONFIRMAR1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCONFIRMAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 690, -1, -1));

        jvolver1.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jvolver1.setText("Volver");
        jvolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvolver1ActionPerformed(evt);
            }
        });
        jPanel2.add(jvolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 690, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel2.setText("VUELOS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel3.setText("EQUIPAJE ADICIONAL");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel1.setText("HORARIO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 460, -1, -1));

        jfondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tabla con 3 columnas (3).png"))); // NOI18N
        jfondo1.setText("jLabel1");
        jPanel2.add(jfondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1365, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jvuelos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvuelos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jvuelos1ActionPerformed

    private void jCONFIRMAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCONFIRMAR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCONFIRMAR1ActionPerformed

    private void jvolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvolver1ActionPerformed
        this.setVisible(false);
        new Interfaz_prinipal().setVisible(true);
    }//GEN-LAST:event_jvolver1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCONFIRMAR1;
    private javax.swing.JComboBox<String> jEquipajeadi2;
    private javax.swing.JComboBox<String> jHora3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jfondo1;
    private javax.swing.JButton jvolver1;
    private javax.swing.JComboBox<String> jvuelos1;
    // End of variables declaration//GEN-END:variables
}
