package interfaces;

import clases.variables;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class interfazdepago extends javax.swing.JFrame {
private ArrayList<variables> listaVariables = new ArrayList<>();

    

    /** Creates new form interfazdepago */
    public interfazdepago() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jVolver = new javax.swing.JButton();
        jLimpiar = new javax.swing.JButton();
        jconfirmar = new javax.swing.JButton();
        jTitulo = new javax.swing.JLabel();
        jnombrecliente = new javax.swing.JTextField();
        jnombre = new javax.swing.JLabel();
        japellidos = new javax.swing.JLabel();
        japellidoclien = new javax.swing.JTextField();
        jelijatipodedocumento = new javax.swing.JComboBox<>();
        jtipodedo = new javax.swing.JLabel();
        jnumerodocumecliente = new javax.swing.JTextField();
        jnumerddc = new javax.swing.JLabel();
        jlabel12 = new javax.swing.JLabel();
        jDia1 = new javax.swing.JTextField();
        jMes1 = new javax.swing.JTextField();
        jAño1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcorreoelectronico = new javax.swing.JTextField();
        jtelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jmetododepago = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jtarjetadecredito = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jVolver.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jVolver.setText("Volver");
        jPanel1.add(jVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 700, -1, -1));

        jLimpiar.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLimpiar.setText("Limpiar");
        jLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 700, -1, -1));

        jconfirmar.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jconfirmar.setText("Confirmar");
        jconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(jconfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 700, -1, -1));

        jTitulo.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jTitulo.setText("REGISTRO DE DATOS PERSONALES Y PAGOS");
        jPanel1.add(jTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));
        jPanel1.add(jnombrecliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 150, -1));

        jnombre.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jnombre.setText("Primer Nombre:");
        jPanel1.add(jnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        japellidos.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        japellidos.setText("Primer Apellido:");
        jPanel1.add(japellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, -1, -1));
        jPanel1.add(japellidoclien, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 150, 150, -1));

        jelijatipodedocumento.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jelijatipodedocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "C.C", "T.I", "PASAPORTE", " " }));
        jPanel1.add(jelijatipodedocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        jtipodedo.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jtipodedo.setText("Tipo De Documento");
        jPanel1.add(jtipodedo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));
        jPanel1.add(jnumerodocumecliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 160, -1));

        jnumerddc.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jnumerddc.setText("Numero de Documento");
        jPanel1.add(jnumerddc, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, -1, 20));

        jlabel12.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jlabel12.setText("Fecha de Nacimiento:");
        jPanel1.add(jlabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));
        jPanel1.add(jDia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 90, -1));
        jPanel1.add(jMes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 100, -1));
        jPanel1.add(jAño1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 80, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel3.setText("Dia");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel4.setText("Mes");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel5.setText("Año");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel6.setText("Informacion De Contacto");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 300, 70));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel7.setText("Telefono o Celular (10 digitos)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 220, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel8.setText("Correo Electronico @");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, -1, -1));
        jPanel1.add(jcorreoelectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 230, -1));
        jPanel1.add(jtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 210, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel9.setText("Informacion De Pago");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 200, -1));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel10.setText("Metodo De pago");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, -1, -1));

        jmetododepago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "VISA", "MASTER CARD", "EFECTY", " " }));
        jPanel1.add(jmetododepago, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, -1, -1));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel11.setText("Tarjeta de Credito:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 540, -1, 20));
        jPanel1.add(jtarjetadecredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, 240, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tabla con 3 columnas (4).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconfirmarActionPerformed

        if (jnombrecliente.getText().isEmpty()
                || japellidoclien.getText().isEmpty()
                || jtelefono.getText().isEmpty()
                || jcorreoelectronico.getText().isEmpty()
                || jDia1.getText().isEmpty()
                || jMes1.getText().isEmpty()
                || jAño1.getText().isEmpty()
                || jelijatipodedocumento.getSelectedIndex() == 0
                || jnumerodocumecliente.getText().isEmpty()
                || jmetododepago.getSelectedIndex() == 0
                || jtarjetadecredito.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos");
        } else { 
            
            String Nombre = jnombrecliente.getText();
            String Apellido = japellidoclien.getText();
            long TL = Long.parseLong(jtelefono.getText());
            String CE = jcorreoelectronico.getText();
            int Dia = Integer.parseInt(jDia1.getText());
            int Mes = Integer.parseInt(jMes1.getText());
            int Año = Integer.parseInt(jAño1.getText());
            String TD = jelijatipodedocumento.getSelectedItem().toString();
            int ND = Integer.parseInt(jnumerodocumecliente.getText());
            String MTDP = jmetododepago.getSelectedItem().toString();
            int TC = Integer.parseInt(jtarjetadecredito.getText());

        variables nuevaVariable = new variables(Nombre, Apellido, Dia, Mes, Año, TD, CE, ND, TL, MTDP, TC);
        listaVariables.add(nuevaVariable);

        String Recibo = "Nombre: " + Nombre + "\nApellido: " + Apellido + "\nTeléfono: " + TL + "\nCorreo: " + CE + "\nFecha de nacimiento: " + Dia + "/" + Mes + "/" + Año + "\nTipo de documento: " + TD + "\nNúmero de documento: " + ND + "\nMétodo de pago: " + MTDP + "\nTarjeta de crédito: " + TC;
        JOptionPane.showMessageDialog(null, Recibo);

            
        }    
    }//GEN-LAST:event_jconfirmarActionPerformed

    private void jLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpiarActionPerformed
        jnombrecliente.setText("");
        japellidoclien.setText("");
        jtelefono.setText("");
        jcorreoelectronico.setText("");
        jDia1.setText("");
        jMes1.setText("");
        jAño1.setText("");
        jelijatipodedocumento.setSelectedIndex(0);
        jnumerodocumecliente.setText("");
        jmetododepago.setSelectedIndex(0);
        jtarjetadecredito.setText("");
    }//GEN-LAST:event_jLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazdepago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazdepago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazdepago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazdepago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazdepago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAño1;
    private javax.swing.JTextField jDia1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLimpiar;
    private javax.swing.JTextField jMes1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTitulo;
    private javax.swing.JButton jVolver;
    private javax.swing.JTextField japellidoclien;
    private javax.swing.JLabel japellidos;
    private javax.swing.JButton jconfirmar;
    private javax.swing.JTextField jcorreoelectronico;
    private javax.swing.JComboBox<String> jelijatipodedocumento;
    private javax.swing.JLabel jlabel12;
    private javax.swing.JComboBox<String> jmetododepago;
    private javax.swing.JLabel jnombre;
    private javax.swing.JTextField jnombrecliente;
    private javax.swing.JLabel jnumerddc;
    private javax.swing.JTextField jnumerodocumecliente;
    private javax.swing.JTextField jtarjetadecredito;
    private javax.swing.JTextField jtelefono;
    private javax.swing.JLabel jtipodedo;
    // End of variables declaration//GEN-END:variables

}
